#!/bin/sh

# Prompt confirmation using rofi
confirm=$(echo -e "No\nYes" | rofi -dmenu -i -p "Do you really want to exit i3?")

# Act based on selection
if [[ "$confirm" == "Yes" ]]; then
  i3-msg exit
fi
