#!/usr/bin/env bash

# Get current working directory of focused kitty window
cwd=$(kitty @ ls | grep -A1 '"is_focused": true' | grep '"cwd"' | sed 's/.*"cwd": "\(.*\)".*/\1/')
echo "$cwd"

# If we got one, open new kitty there
if [ -n "$cwd" ]; then
    kitty --directory="$cwd" &
else
    kitty &
fi
