#!/bin/sh
choice=$(printf "󰣆 Apps\n󰏖 Flatpaks\n󰆍 Programs\n⏻ Power\n󰃬 Calculator\n󰉋 File Explorer\n" | \
    rofi -dmenu -i -p "Menu" | sed 's/^[^ ]* //')
case "$choice" in
    Apps)
        rofi -show run
        ;;
    Flatpaks)
        ~/.config/i3/scripts/flatpak
        ;;
    Programs)
        ~/.config/i3/scripts/programs
        ;;
    Power)
        ~/.config/i3/scripts/power
        ;;
    Calculator)
        rofi -show calc \
            -modi calc \
            -no-show-match \
            -no-sort \
            -calc-command "echo -n '{result}' | xclip -selection clipboard"
        ;;
    "File Explorer")
        thunar
        ;;
esac
